# Mississippi Canyon Protraction Biostratigraphy Heatmap

_Select an age to see the density of wells with biostratigraphic picks of that age._

Data from the U.S. BOEM

In [2]:
from ipywidgets import *


import pandas as pd


# from ipyleaflet import Map, basemaps, WidgetControl, Heatmap

In [3]:
df = pd.read_csv('../MC_bugs.csv')
df = df.dropna()
df.head()

,Unnamed: 0,Lat,Long,API,Point,Report_ID,Total_Report,MD,TVD,Conf_PALEO,AT_IN_PALEO,Conf_ECO,AT_IN_ECO,ECO,Epoch,Age,Species,Age_MA
52,52,28.190977,-88.495469,608174098300,P,1.0,1.0,17911.0,17340.0,DEF,IN,DEF,AT,,Upper Miocene,Tortonian,Discoaster deflandrei,7.246
53,53,28.190977,-88.495469,608174098300,P,1.0,1.0,18660.0,17988.0,POS,IN,DEF,AT,,Middle Miocene,Serravallian,Discoaster sanmiguelensis,11.630
54,54,28.190977,-88.495469,608174098300,P,1.0,1.0,18935.0,18228.0,DEF,AT,DEF,AT,,Middle Miocene,Serravallian,Fohsella fohsi,11.630
55,55,28.190977,-88.495469,608174098300,P,1.0,1.0,18990.0,18276.0,DEF,AT,DEF,AT,,Middle Miocene,Serravallian,Discoaster sanmiguelensis increase,11.630
56,56,28.190977,-88.495469,608174098300,P,1.0,1.0,21425.0,20443.0,DEF,IN,POS,AT,5,Middle Miocene,Serravallian,Fohsella peripheroronda,11.630

In [ ]:
def get_data(age_ma):
    locationsw = df.loc[df['Age_MA'] == age_ma]
    return locationsw[['Lat', 'Long']].values.tolist()

In [ ]:
# m = Map(center=(28.46638886508, -88.85057579029998), zoom=8)

# ages = list(df.Age_MA.unique())
# ages.sort()

# initial_age = 1.8

# age_dropdown = Dropdown(options=ages, value=1.8, description='Age MYA', disabled=False,)

# heatmap = Heatmap(locations=get_data(initial_age), min_opacity=0.6, radius=10)

# m.add_layer(heatmap);

In [ ]:
# def time_change(change):
#     heatmap.locations = get_data(age_dropdown.value)
    
# age_dropdown.observe(time_change, 'value')

# VBox([age_dropdown, m])